<?php
return [
    'db' => [
        'live' => [
            'master' => [
                'driver'    => 'mysql',
                'host'      => '127.0.0.1',
                'port'      => 3306,
                'database'  => 'enter your database',
                'username'  => 'enter your username',
                'password'  => 'enter your password',
                'charset'   => 'utf8',
                'collation' => 'utf8_unicode_ci',
                'prefix'    => '',
            ],
            'slave01' => [
                'driver'    => 'mysql',
                'host'      => '127.0.0.1',
                'port'      => 3306,
                'database'  => 'enter your database',
                'username'  => 'enter your username',
                'password'  => 'enter your password',
                'charset'   => 'utf8',
                'collation' => 'utf8_unicode_ci',
                'prefix'    => '',
            ],
            'slave02' => [
                'driver'    => 'mysql',
                'host'      => '127.0.0.1',
                'port'      => 3306,
                'database'  => 'enter your database',
                'username'  => 'enter your username',
                'password'  => 'enter your password',
                'charset'   => 'utf8',
                'collation' => 'utf8_unicode_ci',
                'prefix'    => '',
            ],
            'slave03' => [
                'driver'    => 'mysql',
                'host'      => '127.0.0.1',
                'port'      => 3306,
                'database'  => 'enter your database',
                'username'  => 'enter your username',
                'password'  => 'enter your password',
                'charset'   => 'utf8',
                'collation' => 'utf8_unicode_ci',
                'prefix'    => '',
            ],
            'slave04' => [
                'driver'    => 'mysql',
                'host'      => '127.0.0.1',
                'port'      => 3306,
                'database'  => 'enter your database',
                'username'  => 'enter your username',
                'password'  => 'enter your password',
                'charset'   => 'utf8',
                'collation' => 'utf8_unicode_ci',
                'prefix'    => '',
            ],
        ],
        'staging' => [
            'master' => [
                'driver'    => 'mysql',
                'host'      => '127.0.0.1',
                'port'      => 3306,
                'database'  => 'enter your database',
                'username'  => 'enter your username',
                'password'  => 'enter your password',
                'charset'   => 'utf8',
                'collation' => 'utf8_unicode_ci',
                'prefix'    => '',
            ],
            'slave01' => [
                'driver'    => 'mysql',
                'host'      => '127.0.0.1',
                'port'      => 3306,
                'database'  => 'enter your database',
                'username'  => 'enter your username',
                'password'  => 'enter your password',
                'charset'   => 'utf8',
                'collation' => 'utf8_unicode_ci',
                'prefix'    => '',
            ],
            'slave02' => [
                'driver'    => 'mysql',
                'host'      => '127.0.0.1',
                'port'      => 3306,
                'database'  => 'enter your database',
                'username'  => 'enter your username',
                'password'  => 'enter your password',
                'charset'   => 'utf8',
                'collation' => 'utf8_unicode_ci',
                'prefix'    => '',
            ],
            'slave03' => [
                'driver'    => 'mysql',
                'host'      => '127.0.0.1',
                'port'      => 3306,
                'database'  => 'enter your database',
                'username'  => 'enter your username',
                'password'  => 'enter your password',
                'charset'   => 'utf8',
                'collation' => 'utf8_unicode_ci',
                'prefix'    => '',
            ],
            'slave04' => [
                'driver'    => 'mysql',
                'host'      => '127.0.0.1',
                'port'      => 3306,
                'database'  => 'enter your database',
                'username'  => 'enter your username',
                'password'  => 'enter your password',
                'charset'   => 'utf8',
                'collation' => 'utf8_unicode_ci',
                'prefix'    => '',
            ],
        ],
        'develop' => [
            'master' => [
                'driver'    => 'mysql',
                'host'      => '127.0.0.1',
                'port'      => 3306,
                'database'  => 'enter your database',
                'username'  => 'enter your username',
                'password'  => 'enter your password',
                'charset'   => 'utf8',
                'collation' => 'utf8_unicode_ci',
                'prefix'    => '',
            ],
            'slave01' => [
                'driver'    => 'mysql',
                'host'      => '127.0.0.1',
                'port'      => 3307,
                'database'  => 'enter your database',
                'username'  => 'enter your username',
                'password'  => 'enter your password',
                'charset'   => 'utf8',
                'collation' => 'utf8_unicode_ci',
                'prefix'    => '',
            ],
            'slave02' => [
                'driver'    => 'mysql',
                'host'      => '127.0.0.1',
                'port'      => 3307,
                'database'  => 'enter your database',
                'username'  => 'enter your username',
                'password'  => 'enter your password',
                'charset'   => 'utf8',
                'collation' => 'utf8_unicode_ci',
                'prefix'    => '',
            ],
            'slave03' => [
                'driver'    => 'mysql',
                'host'      => '127.0.0.1',
                'port'      => 3308,
                'database'  => 'enter your database',
                'username'  => 'enter your username',
                'password'  => 'enter your password',
                'charset'   => 'utf8',
                'collation' => 'utf8_unicode_ci',
                'prefix'    => '',
            ],
            'slave04' => [
                'driver'    => 'mysql',
                'host'      => '127.0.0.1',
                'port'      => 3308,
                'database'  => 'enter your database',
                'username'  => 'enter your username',
                'password'  => 'enter your password',
                'charset'   => 'utf8',
                'collation' => 'utf8_unicode_ci',
                'prefix'    => '',
            ],
        ],
        'local' => [
            'master' => [
                'driver'    => 'mysql',
                'host'      => '127.0.0.1',
                'port'      => 3306,
                'database'  => 'enter your database',
                'username'  => 'enter your username',
                'password'  => 'enter your password',
                'charset'   => 'utf8',
                'collation' => 'utf8_unicode_ci',
                'prefix'    => '',
            ],
            'slave01' => [
                'driver'    => 'mysql',
                'host'      => '127.0.0.1',
                'port'      => 3307,
                'database'  => 'enter your database',
                'username'  => 'enter your username',
                'password'  => 'enter your password',
                'charset'   => 'utf8',
                'collation' => 'utf8_unicode_ci',
                'prefix'    => '',
            ],
            'slave02' => [
                'driver'    => 'mysql',
                'host'      => '127.0.0.1',
                'port'      => 3307,
                'database'  => 'enter your database',
                'username'  => 'enter your username',
                'password'  => 'enter your password',
                'charset'   => 'utf8',
                'collation' => 'utf8_unicode_ci',
                'prefix'    => '',
            ],
            'slave03' => [
                'driver'    => 'mysql',
                'host'      => '127.0.0.1',
                'port'      => 3308,
                'database'  => 'enter your database',
                'username'  => 'enter your username',
                'password'  => 'enter your password',
                'charset'   => 'utf8',
                'collation' => 'utf8_unicode_ci',
                'prefix'    => '',
            ],
            'slave04' => [
                'driver'    => 'mysql',
                'host'      => '127.0.0.1',
                'port'      => 3308,
                'database'  => 'enter your database',
                'username'  => 'enter your username',
                'password'  => 'enter your password',
                'charset'   => 'utf8',
                'collation' => 'utf8_unicode_ci',
                'prefix'    => '',
            ],
        ],
    ],
];
